steps:
# Run CI/CD for each individual service.
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', './client', '--config', 'cloudbuild.yaml']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', './server', '--config', 'cloudbuild.yaml']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', './worker', '--config', 'cloudbuild.yaml']
  waitFor: ['-']

timeout: 240s

# A more automated way to look for all cloudbuild.yaml.
# Inspired by: https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/cloudbuild.yaml
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     for d in */; do
#       config="${d}cloudbuild.yaml"
#       if [[ ! -f "${config}" ]]; then
#         continue
#       fi

#       echo "Building $d ... "
#       (
#         gcloud builds submit $d --config=${config}
#       ) &
#     done
#     wait
# Apply Kubernetes configs.
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'k8s']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=<cluster-zone>'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=<cluster-name>'
