steps:
# Build client image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fibonacci-client', './client']
# Build server image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fibonacci-server', './server']
# Build worker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fibonacci-worker', './worker']

# Upload images to GCR.
images:
- 'gcr.io/$PROJECT_ID/fibonacci-client'
- 'gcr.io/$PROJECT_ID/fibonacci-server'
- 'gcr.io/$PROJECT_ID/fibonacci-worker'
