steps:
# Build client image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-client:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-client:$COMMIT_SHA', 
    '.']
  dir: './client'
  id: 'client-build'
  waitFor: ['-']
# Build server image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA', 
    '.']
  dir: './server'
  id: 'server-build'
  waitFor: ['-']
# Build worker image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-worker:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-worker:$COMMIT_SHA', 
    '.']
  dir: './worker'
  id: 'worker-build'
  waitFor: ['-']

# Push client image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-client:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-client:$COMMIT_SHA ||
    echo "skipping..."
  waitFor: ['client-build']
# Push server image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-server:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA ||
    echo "skipping..."
  waitFor: ['server-build']
# Push worker image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-worker:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-worker:$COMMIT_SHA ||
    echo "skipping..."
  waitFor: ['worker-build']

# Apply Kubernetes configs.
# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'k8s']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=<cluster-zone>'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=<cluster-name>'
# Push image to GKE cluster.
# - name: 'gcr.io/cloud-builders/kubectl'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     [[ "$BRANCH_NAME" == "master" ]] && /builders/kubectl.bash set image deployment [deployment] [container]=gcr.io/$PROJECT_ID/[image]:[tag]
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=[zone]'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=[cluster]'
# Upload images to GCR and DockerHub.
# images:
# - 'gcr.io/$PROJECT_ID/fibonacci-client'
# - 'gcr.io/$PROJECT_ID/fibonacci-server'
# - 'gcr.io/$PROJECT_ID/fibonacci-worker'
# - 'jjzhan/fibonacci-client'
# - 'jjzhan/fibonacci-server'
# - 'jjzhan/fibonacci-worker'
