# Use Kaniko to build, cache and upload docker images.
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - -c ./client
    - --destination=gcr.io/$PROJECT_ID/fibonacci-client
    - --cache=true
    - --cache-ttl=6h
    waitFor: ['-']
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - -c ./server
    - --destination=gcr.io/$PROJECT_ID/fibonacci-server
    - --cache=true
    - --cache-ttl=6h
    waitFor: ['-']
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - -c ./worker  
    - --destination=gcr.io/$PROJECT_ID/fibonacci-worker
    - --cache=true
    - --cache-ttl=6h
    waitFor: ['-']
