steps:
# Build client production image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/fibonacci-client:latest',
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-client:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-client:$COMMIT_SHA', 
    '.']
  dir: './client'
  id: 'client-build'
  waitFor: ['-']
# Build server production image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/fibonacci-server:latest',
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA', 
    '.']
  dir: './server'
  id: 'server-build'
  waitFor: ['-']
# Build worker production image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/fibonacci-worker:latest',
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-worker:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-worker:$COMMIT_SHA', 
    '.']
  dir: './worker'
  id: 'worker-build'
  waitFor: ['-']

# Push client image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-client:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-client:$COMMIT_SHA ||
    echo "skipping..."
  id: 'client-push'
  waitFor: ['client-build']
# Push server image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-server:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA ||
    echo "skipping..."
  id: 'server-push'
  waitFor: ['server-build']
# Push worker image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-worker:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-worker:$COMMIT_SHA ||
    echo "skipping..."
  id: 'worker-push'
  waitFor: ['worker-build']
# Configure to point to the GKE Kubernetes cluster.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    gcloud container clusters get-credentials fibonacci-cluster-1 --zone us-west1-a ||
    echo "skipping..."
  id: 'cluster-config'
  waitFor: ['-']
# Apply Kubernetes configs on master branch change.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    kubectl apply -f k8s || 
    echo "skipping..."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=fibonacci-cluster-1'
  id: 'apply-kube-configs'
  waitFor: ['cluster-config', 'client-push', 'server-push', 'worker-push']
# Push image to GKE cluster on master branch change.
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    kubectl set image deployments/client-deployment client=gcr.io/$PROJECT_ID/fibonacci-client:$COMMIT_SHA &&
    kubectl set image deployments/server-deployment server=gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA &&
    kubectl set image deployments/worker-deployment worker=gcr.io/$PROJECT_ID/fibonacci-worker:$COMMIT_SHA ||
    echo "skipping..."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=fibonacci-cluster-1'
  id: 'set-kube-images'
  waitFor: ['apply-kube-configs']
# Will enable once I get a rough time.
#timeout: 240s
