apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      component: web
  template:
    metadata: 
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: jjzhan/fibonacci-client
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "150Mi"
              cpu: "150m"
          ports:
            - containerPort: 3000
