apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template: 
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "250m"
          ports: 
            - containerPort: 6379
