apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec: 
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: jjzhan/fibonacci-server
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "150Mi"
              cpu: "150m"
          ports:
            - containerPort: 5000
          env:
            - name: HTTP_PORT
              value: "5000"
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CON_TYPE
              value: "tcp"
            - name: PGUSER
              value: postgres
            - name: PGSSLMODE 
              value: "disable"
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
