steps:
# Build server image.
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--cache-from', 'gcr.io/$PROJECT_ID/fibonacci-server:latest',
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:latest', 
    '-t', 'gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA', 
    '.']
  id: 'server-build'
  waitFor: ['-']
# Push server image to GCR on master branch change.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && 
    docker push gcr.io/$PROJECT_ID/fibonacci-server:latest &&
    docker push gcr.io/$PROJECT_ID/fibonacci-server:$COMMIT_SHA ||
    echo "skipping..."
  waitFor: ['server-build']
# Push images to GKE cluster.
# - name: 'gcr.io/cloud-builders/kubectl'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     [[ "$BRANCH_NAME" == "master" ]] && /builders/kubectl.bash set image deployment [deployment] [container]=gcr.io/$PROJECT_ID/[image]:[tag]
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=[zone]'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=[cluster]'

# A global timeout of 4min.
timeout: 240s
